// Phase 5 additions
const extraCode = {
  "stack": {
    "py": "class Stack:\n    def __init__(self):\n        self.items = []\n    def push(self, item):\n        self.items.append(item)\n    def pop(self):\n        return self.items.pop()\n    def peek(self):\n        return self.items[-1]\n    def is_empty(self):\n        return len(self.items) == 0",
    "cpp": "#include <vector>\ntemplate<typename T>\nclass Stack {\n    std::vector<T> items;\npublic:\n    void push(T val) { items.push_back(val); }\n    T pop() { T v = items.back(); items.pop_back(); return v; }\n    T peek() { return items.back(); }\n    bool isEmpty() { return items.empty(); }\n};"
  },
  "queue": {
    "py": "from collections import deque\nclass Queue:\n    def __init__(self):\n        self.items = deque()\n    def enqueue(self, item):\n        self.items.append(item)\n    def dequeue(self):\n        return self.items.popleft()\n    def front(self):\n        return self.items[0]",
    "cpp": "#include <queue>\ntemplate<typename T>\nclass Queue {\n    std::queue<T> q;\npublic:\n    void enqueue(T val) { q.push(val); }\n    T dequeue() { T v = q.front(); q.pop(); return v; }\n    T front() { return q.front(); }\n    bool isEmpty() { return q.empty(); }\n};"
  },
  "linkedlist": {
    "py": "class Node:\n    def __init__(self, val):\n        self.val = val\n        self.next = None\n\nclass LinkedList:\n    def __init__(self):\n        self.head = None\n    def append(self, val):\n        if not self.head:\n            self.head = Node(val); return\n        curr = self.head\n        while curr.next: curr = curr.next\n        curr.next = Node(val)",
    "cpp": "struct Node {\n    int val;\n    Node* next = nullptr;\n    Node(int v): val(v) {}\n};\nclass LinkedList {\n    Node* head = nullptr;\npublic:\n    void append(int val) {\n        if (!head) { head = new Node(val); return; }\n        Node* curr = head;\n        while (curr->next) curr = curr->next;\n        curr->next = new Node(val);\n    }\n};"
  },
  "binarysearch": {
    "py": "def binary_search(arr, target):\n    low, high = 0, len(arr) - 1\n    while low <= high:\n        mid = (low + high) // 2\n        if arr[mid] == target:\n            return mid\n        elif arr[mid] < target:\n            low = mid + 1\n        else:\n            high = mid - 1\n    return -1",
    "cpp": "int binarySearch(const std::vector<int>& arr, int target) {\n    int low = 0, high = (int)arr.size() - 1;\n    while (low <= high) {\n        int mid = low + (high - low) / 2;\n        if (arr[mid] == target) return mid;\n        if (arr[mid] < target) low = mid + 1;\n        else high = mid - 1;\n    }\n    return -1;\n}"
  },
  "bubbleSort": {
    "py": "def bubble_sort(arr):\n    n = len(arr)\n    for i in range(n):\n        swapped = False\n        for j in range(0, n - i - 1):\n            if arr[j] > arr[j + 1]:\n                arr[j], arr[j + 1] = arr[j + 1], arr[j]\n                swapped = True\n        if not swapped: break\n    return arr",
    "cpp": "void bubbleSort(std::vector<int>& arr) {\n    int n = arr.size();\n    for (int i = 0; i < n; i++) {\n        bool swapped = false;\n        for (int j = 0; j < n - i - 1; j++) {\n            if (arr[j] > arr[j + 1]) {\n                std::swap(arr[j], arr[j + 1]);\n                swapped = true;\n            }\n        }\n        if (!swapped) break;\n    }\n}"
  },
  "quicksort": {
    "py": "def quick_sort(arr):\n    if len(arr) <= 1: return arr\n    pivot = arr[len(arr) // 2]\n    left = [x for x in arr if x < pivot]\n    mid = [x for x in arr if x == pivot]\n    right = [x for x in arr if x > pivot]\n    return quick_sort(left) + mid + quick_sort(right)",
    "cpp": "void quickSort(std::vector<int>& arr, int low, int high) {\n    if (low >= high) return;\n    int pivot = arr[high], i = low - 1;\n    for (int j = low; j < high; j++) {\n        if (arr[j] < pivot) std::swap(arr[++i], arr[j]);\n    }\n    std::swap(arr[i + 1], arr[high]);\n    int pi = i + 1;\n    quickSort(arr, low, pi - 1);\n    quickSort(arr, pi + 1, high);\n}"
  },
  "websocket": {
    "py": "import asyncio, websockets\n\nasync def connect():\n    async with websockets.connect('wss://api.com/live') as ws:\n        await ws.send('Hello Server!')\n        msg = await ws.recv()\n        print('Live feed:', msg)\n\nasyncio.run(connect())",
    "cpp": "#include <boost/beast/websocket.hpp>\nnamespace ws = boost::beast::websocket;\n// 1. Establish TCP socket\n// 2. ws.handshake(\"api.com\", \"/live\");\n// 3. ws.write(net::buffer(\"Hello!\"));\n// 4. ws.read(buffer);"
  },
  "vector_embeddings": {
    "py": "import numpy as np\n\ndef cosine_similarity(vec_a, vec_b):\n    a = np.array(vec_a)\n    b = np.array(vec_b)\n    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))\n\n# Query similarity\nscore = cosine_similarity([0.8, 0.6], [0.85, 0.55])",
    "cpp": "#include <vector>\n#include <cmath>\n#include <numeric>\n\ndouble cosineSimilarity(const std::vector<double>& a, const std::vector<double>& b) {\n    double dot = 0.0, normA = 0.0, normB = 0.0;\n    for (size_t i = 0; i < a.size(); ++i) {\n        dot += a[i] * b[i];\n        normA += a[i] * a[i];\n        normB += b[i] * b[i];\n    }\n    return dot / (std::sqrt(normA) * std::sqrt(normB));\n}"
  },
  "perceptron": {
    "py": "class Perceptron:\n    def __init__(self, weights, bias):\n        self.w = weights\n        self.b = bias\n    def predict(self, inputs):\n        z = sum(x * w for x, w in zip(inputs, self.w)) + self.b\n        return 1 if z >= 0 else 0",
    "cpp": "#include <vector>\n#include <numeric>\n\nclass Perceptron {\n    std::vector<double> weights;\n    double bias;\npublic:\n    Perceptron(std::vector<double> w, double b): weights(w), bias(b) {}\n    int predict(const std::vector<double>& inputs) {\n        double z = bias;\n        for (size_t i = 0; i < inputs.size(); ++i) z += inputs[i] * weights[i];\n        return z >= 0.0 ? 1 : 0;\n    }\n};"
  },
  "token_bucket": {
    "py": "import time\n\nclass TokenBucket:\n    def __init__(self, capacity, refill_rate):\n        self.capacity = capacity\n        self.tokens = capacity\n        self.refill_rate = refill_rate\n        self.last = time.time()\n    def allow_request(self):\n        now = time.time()\n        self.tokens = min(self.capacity, self.tokens + (now - self.last) * self.refill_rate)\n        self.last = now\n        if self.tokens >= 1:\n            self.tokens -= 1\n            return True\n        return False # 429",
    "cpp": "#include <chrono>\n#include <algorithm>\n\nclass TokenBucket {\n    double capacity, tokens, refillRate;\n    std::chrono::steady_clock::time_point lastRefill;\npublic:\n    TokenBucket(double cap, double rate): capacity(cap), tokens(cap), refillRate(rate),\n        lastRefill(std::chrono::steady_clock::now()) {}\n    bool allow() {\n        auto now = std::chrono::steady_clock::now();\n        double elapsed = std::chrono::duration<double>(now - lastRefill).count();\n        tokens = std::min(capacity, tokens + elapsed * refillRate);\n        lastRefill = now;\n        if (tokens >= 1.0) { tokens -= 1.0; return true; }\n        return false;\n    }\n};"
  },
  "a_star": {
    "py": "import heapq\n\ndef astar(start, goal, h, neighbors):\n    open_set = [(h(start, goal), start)]\n    g = {start: 0}\n    while open_set:\n        f, node = heapq.heappop(open_set)\n        if node == goal:\n            return g[node]\n        for nxt, w in neighbors(node):\n            tentative = g[node] + w\n            if tentative < g.get(nxt, float('inf')):\n                g[nxt] = tentative\n                heapq.heappush(open_set, (tentative + h(nxt, goal), nxt))\n    return -1",
    "cpp": "#include <queue>\n#include <unordered_map>\n#include <vector>\n\ndouble astar(int start, int goal, double (*h)(int,int),\n             std::vector<std::pair<int,double>> (*neighbors)(int)) {\n    std::priority_queue<std::pair<double,int>, std::vector<std::pair<double,int>>, std::greater<>> open;\n    std::unordered_map<int,double> g{{start, 0}};\n    open.push({h(start, goal), start});\n    while (!open.empty()) {\n        auto [f, node] = open.top(); open.pop();\n        if (node == goal) return g[node];\n        for (auto& [nxt, w] : neighbors(node)) {\n            double t = g[node] + w;\n            if (!g.count(nxt) || t < g[nxt]) {\n                g[nxt] = t;\n                open.push({t + h(nxt, goal), nxt});\n            }\n        }\n    }\n    return -1;\n}"
  },
  "n_queens": {
    "py": "def solve_n_queens(n):\n    cols, d1, d2, board, res = set(), set(), set(), [], []\n    def place(row):\n        if row == n:\n            res.append(list(board)); return\n        for col in range(n):\n            if col in cols or (row - col) in d1 or (row + col) in d2:\n                continue\n            cols.add(col); d1.add(row - col); d2.add(row + col); board.append(col)\n            place(row + 1)\n            board.pop(); cols.discard(col); d1.discard(row - col); d2.discard(row + col)\n    place(0)\n    return res",
    "cpp": "#include <vector>\n#include <unordered_set>\n\nclass NQueens {\n    int n; std::unordered_set<int> cols, d1, d2; std::vector<int> board;\npublic:\n    NQueens(int n): n(n) {}\n    bool place(int row) {\n        if (row == n) return true;\n        for (int col = 0; col < n; col++) {\n            if (cols.count(col) || d1.count(row - col) || d2.count(row + col)) continue;\n            cols.insert(col); d1.insert(row - col); d2.insert(row + col); board.push_back(col);\n            if (place(row + 1)) return true;\n            board.pop_back(); cols.erase(col); d1.erase(row - col); d2.erase(row + col);\n        }\n        return false;\n    }\n};"
  },
  "kadane": {
    "py": "def max_subarray(nums):\n    best = cur = nums[0]\n    for x in nums[1:]:\n        cur = max(x, cur + x)\n        best = max(best, cur)\n    return best",
    "cpp": "#include <algorithm>\n#include <vector>\n\nint maxSubarray(const std::vector<int>& nums) {\n    int best = nums[0], cur = nums[0];\n    for (size_t i = 1; i < nums.size(); ++i) {\n        cur = std::max(nums[i], cur + nums[i]);\n        best = std::max(best, cur);\n    }\n    return best;\n}"
  },
  "union_find": {
    "py": "class DSU:\n    def __init__(self, n):\n        self.parent = list(range(n))\n        self.rank = [0] * n\n    def find(self, x):\n        while self.parent[x] != x:\n            self.parent[x] = self.parent[self.parent[x]]\n            x = self.parent[x]\n        return x\n    def union(self, a, b):\n        ra, rb = self.find(a), self.find(b)\n        if ra == rb:\n            return False\n        if self.rank[ra] < self.rank[rb]:\n            ra, rb = rb, ra\n        self.parent[rb] = ra\n        if self.rank[ra] == self.rank[rb]:\n            self.rank[ra] += 1\n        return True",
    "cpp": "#include <vector>\n#include <numeric>\n\nclass DSU {\n    std::vector<int> parent, rank_;\npublic:\n    DSU(int n): parent(n), rank_(n, 0) { std::iota(parent.begin(), parent.end(), 0); }\n    int find(int x) {\n        if (parent[x] != x) parent[x] = find(parent[x]);\n        return parent[x];\n    }\n    bool unite(int a, int b) {\n        int ra = find(a), rb = find(b);\n        if (ra == rb) return false;\n        if (rank_[ra] < rank_[rb]) std::swap(ra, rb);\n        parent[rb] = ra;\n        if (rank_[ra] == rank_[rb]) rank_[ra]++;\n        return true;\n    }\n};"
  },
  "monotonic_stack": {
    "py": "def next_greater(nums):\n    res = [-1] * len(nums)\n    stack = []\n    for i, x in enumerate(nums):\n        while stack and nums[stack[-1]] < x:\n            res[stack.pop()] = x\n        stack.append(i)\n    return res",
    "cpp": "#include <vector>\n#include <stack>\n\nstd::vector<int> nextGreater(const std::vector<int>& nums) {\n    std::vector<int> res(nums.size(), -1);\n    std::stack<int> st;\n    for (int i = 0; i < (int)nums.size(); ++i) {\n        while (!st.empty() && nums[st.top()] < nums[i]) {\n            res[st.top()] = nums[i]; st.pop();\n        }\n        st.push(i);\n    }\n    return res;\n}"
  },
  "bellman_ford": {"js":"function bellmanFord(nodes, edges, src) {\n  const dist = {}; nodes.forEach(n => dist[n] = Infinity);\n  dist[src] = 0;\n  for (let i = 1; i < nodes.length; i++)\n    for (const [u, v, w] of edges)\n      if (dist[u] + w < dist[v]) dist[v] = dist[u] + w;\n  return dist;","py":"def bellman_ford(nodes, edges, src):\n    dist = {n: float('inf') for n in nodes}\n    dist[src] = 0\n    for _ in range(len(nodes) - 1):\n        for u, v, w in edges:\n            if dist[u] + w < dist[v]:\n                dist[v] = dist[u] + w\n    return dist","cpp":"// Bellman-Ford\nunordered_map<string,long long> dist;\nfor (auto& n : nodes) dist[n] = LLONG_MAX;\ndist[src] = 0;\nfor (int i = 1; i < (int)nodes.size(); i++)\n  for (auto& [u, v, w] : edges)\n    if (dist[u] + w < dist[v]) dist[v] = dist[u] + w;"},
  "kruskal": {"js":"function kruskal(n, edges) {\n  edges.sort((a, b) => a[2] - b[2]);\n  const dsu = new DSU(n), mst = [];\n  for (const [u, v, w] of edges)\n    if (dsu.union(u, v)) mst.push([u, v, w]);\n  return mst;","py":"def kruskal(n, edges):\n    parent = list(range(n))\n    def find(x):\n        while parent[x] != x:\n            parent[x] = parent[parent[x]]\n            x = parent[x]\n        return x\n    mst = []\n    for u, v, w in sorted(edges, key=lambda e: e[2]):\n        ru, rv = find(u), find(v)\n        if ru != rv:\n            parent[ru] = rv\n            mst.append((u, v, w))\n    return mst","cpp":"// Kruskal: sort edges by weight + DSU find/union"},
  "segment_tree": {"js":"class SegTree {\n  constructor(arr) {\n    this.n = arr.length;\n    this.t = new Array(2 * this.n);\n    for (let i = 0; i < this.n; i++) this.t[this.n + i] = arr[i];\n    for (let i = this.n - 1; i > 0; i--)\n      this.t[i] = this.t[2*i] + this.t[2*i+1];\n  }\n}","py":"n = len(arr)\ntree = [0] * (2 * n)\nfor i in range(n):\n    tree[n + i] = arr[i]\nfor i in range(n - 1, 0, -1):\n    tree[i] = tree[2*i] + tree[2*i+1]","cpp":"// Segment tree - iterative, size 2n"},
  "huffman": {"js":"function huffman(freqs) {\n  const pq = Object.entries(freqs).map(([sym, f]) => ({ sym, f }));\n  while (pq.length > 1) {\n    pq.sort((a, b) => a.f - b.f);\n    const a = pq.shift(), b = pq.shift();\n    pq.push({ sym: a.sym + b.sym, f: a.f + b.f, kids: [a, b] });\n  }\n  return pq[0];\n}","py":"import heapq\ndef huffman(freqs):\n    h = [(f, sym) for sym, f in freqs.items()]\n    heapq.heapify(h)\n    while len(h) > 1:\n        f1, a = heapq.heappop(h)\n        f2, b = heapq.heappop(h)\n        heapq.heappush(h, (f1 + f2, a + b))\n    return h[0]","cpp":"// Huffman with priority_queue<pair<int,string>, greater<>>"}
};

if (typeof module !== "undefined" && module.exports) {
  module.exports = extraCode;
}
